services:
  db:
    image: postgres:15-alpine
    container_name: sync-event-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: syncevent_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - sync-network

  backend:
    build:
      context: .
      dockerfile: apps/backend/Dockerfile
    container_name: sync-event-backend
    volumes:
      - .:/app
      - /app/node_modules
      - /app/apps/backend/node_modules
    environment:
      DATABASE_URL: "postgresql://user:password@db:5432/syncevent_db?schema=public"
      PORT: 3000
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - sync-network
    command: pnpm --filter backend start:dev

  pgadmin:
    image: dpage/pgadmin4
    container_name: sync-event-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db
    networks:
      - sync-network

networks:
  sync-network:
    driver: bridge

volumes:
  pgdata: